/**
 * trip-config.js: Bulgarian identity, interface copy, and theme for the China family journal.
 * Defines window.GALLERY_TRIP_CONFIG for the reusable static trip gallery.
 */

window.GALLERY_TRIP_CONFIG = {
  language: "bg",
  locale: "bg-BG",
  pageTitle: "Пътуване до Китай - юли 2025",
  heroEyebrow: "Семеен пътепис",
  heading: "Пътуване до Китай - юли 2025",
  subtitle: "Едно пътешествие на семейство Христови",
  tripFacts: "",
  pageDescription: "Пътуване до Китай през юли 2025 — снимки, видеа и разкази на семейство Христови.",
  theme: {
    canvas: "#f4efe5",
    surface: "#fbf8f1",
    surfaceRaised: "#fffdf8",
    ink: "#27231e",
    inkSoft: "#665f55",
    inkMuted: "#7a7268",
    accent: "#9f2f2a",
    accentStrong: "#74201e",
    accentSoft: "#f2dfd8",
    secondary: "#315e54",
    secondarySoft: "#dce7df",
    focus: "#166b9a",
    heroWash: "rgb(159 47 42 / 6%)"
  },
  labels: {
    skipLink: "Към съдържанието",
    openNavigator: "Отвори избора на събитие",
    events: "Събития",
    navigatorAria: "Събития от пътуването",
    routeKicker: "Маршрут",
    journalHeading: "Дневник на пътуването",
    closeNavigator: "Затвори избора на събитие",
    searchLabel: "Търсене в събитията",
    searchPlaceholder: "Място или преживяване",
    eventsByDate: "Събития по дата",
    loadingTrip: "Зареждане на пътуването…",
    lightboxTitle: "Преглед на медия",
    close: "Затвори",
    missingElementsLog: "Липсват задължителни елементи на галерията:",
    eventCountSingular: "{count} събитие",
    eventCountPlural: "{count} събития",
    eventFallbackPrefix: "Събитие",
    untitledEvent: "Събитие без заглавие",
    unknownDate: "Без посочена дата",
    noSearchResults: "Няма събития, които отговарят на търсенето.",
    filteredSummary: "Показани {visible} от {total}",
    staleLoad: "Остаряло зареждане на събитие.",
    missingEventData: "Липсват данни за събитието {event}.",
    eventLoadFailed: "Неуспешно зареждане на {path}.",
    imageNoun: "снимка",
    videoNoun: "видео",
    currentEventFallback: "събитието",
    openMedia: "Отвори {media} {number}: {event}",
    imageAlt: "Снимка {number} — {event}",
    videoAlt: "Кадър от видео {number} — {event}",
    imageUnavailable: "Снимката не може да се зареди. Опитайте да я отворите.",
    videoUnavailable: "Кадърът не може да се зареди. Видеото може да се отвори.",
    retry: "Опитайте отново",
    emptyEvent: "За това събитие няма съдържание за показване.",
    loadingContent: "Зареждане на снимките и разказите…",
    contentLoading: "Съдържанието се зарежда.",
    contentLoadFailed: "Съдържанието не можа да се зареди.",
    eventFailure: "Възникна проблем при зареждането на това събитие. Проверете връзката и опитайте отново.",
    videoUrlErrorLog: "Адресът за видеото не може да бъде обработен:",
    mediaPreview: "Преглед на {media}: {event}",
    eventErrorLog: "Събитието не можа да се зареди:",
    tripUnavailable: "Пътуването не може да бъде заредено",
    registryMissing: "Списъкът със събития е празен.",
    noTripEvents: "В момента няма достъпни събития от пътуването.",
    noEvents: "Няма събития"
  }
};
