window.GALLERY_TRIP_CONFIG = {
  "language": "bg",
  "locale": "bg-BG",
  "pageTitle": "Португалия 2026",
  "heading": "Португалия 2026",
  "heroEyebrow": "Семеен пътепис за пътуване до Португалия",
  "subtitle": "Период от 5 септември до 12 септември 2026 г.",
  "pageDescription": "Семеен пътепис със снимки, видеа и разкази от пътуване до Португалия",
  "tripFacts": "",
  "labels": {
    "skipLink": "Към съдържанието",
    "openNavigator": "Отвори избора на събитие",
    "events": "Събития",
    "navigatorAria": "Събития от пътуването",
    "routeKicker": "Маршрут",
    "journalHeading": "Дневник на пътуването",
    "closeNavigator": "Затвори избора на събитие",
    "searchLabel": "Търсене в събитията",
    "searchPlaceholder": "Място или преживяване",
    "eventsByDate": "Събития по дата",
    "loadingTrip": "Зареждане на пътуването…",
    "lightboxTitle": "Преглед на медия",
    "close": "Затвори",
    "missingElementsLog": "Липсват задължителни елементи на галерията:",
    "eventCountSingular": "{count} събитие",
    "eventCountPlural": "{count} събития",
    "eventFallbackPrefix": "Събитие",
    "untitledEvent": "Събитие без заглавие",
    "unknownDate": "Без посочена дата",
    "noSearchResults": "Няма събития, които отговарят на търсенето.",
    "filteredSummary": "Показани {visible} от {total}",
    "staleLoad": "Остаряло зареждане на събитие.",
    "missingEventData": "Липсват данни за събитието {event}.",
    "eventLoadFailed": "Неуспешно зареждане на {path}.",
    "imageNoun": "снимка",
    "videoNoun": "видео",
    "currentEventFallback": "събитието",
    "openMedia": "Отвори {media} {number}: {event}",
    "imageAlt": "Снимка {number} — {event}",
    "videoAlt": "Кадър от видео {number} — {event}",
    "imageUnavailable": "Снимката не може да се зареди. Опитайте да я отворите.",
    "videoUnavailable": "Кадърът не може да се зареди. Видеото може да се отвори.",
    "retry": "Опитайте отново",
    "emptyEvent": "За това събитие няма съдържание за показване.",
    "loadingContent": "Зареждане на снимките и разказите…",
    "contentLoading": "Съдържанието се зарежда.",
    "contentLoadFailed": "Съдържанието не можа да се зареди.",
    "eventFailure": "Възникна проблем при зареждането на това събитие. Проверете връзката и опитайте отново.",
    "videoUrlErrorLog": "Адресът за видеото не може да бъде обработен:",
    "mediaPreview": "Преглед на {media}: {event}",
    "eventErrorLog": "Събитието не можа да се зареди:",
    "tripUnavailable": "Нов пътепис",
    "registryMissing": "Все още няма добавени части.",
    "noTripEvents": "Добавете първата част чрез редактора.",
    "noEvents": "Няма събития"
  },
  "theme": {}
};
